name: Dependabot auto merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run build

      - name: Lint packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run lint

      - name: Test packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run test

      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
