name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install dependencies 
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
        
    - name: Build packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run build
        
    - name: Lint packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run lint
    
    - name: Setup npm auth token
      run: echo "npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    
    - name: Publish packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run publish --no-verify-access --loglevel silly
