name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Setup yarn
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    
    - name: Setup node auth token
      run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    
    - name: Publish
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run publish
